FROM codeship/aws-deployment

RUN apt install -y git
RUN git clone https://github.com/tfutils/tfenv.git ~/.tfenv
RUN ln -s ~/.tfenv/bin/* /usr/local/bin
RUN which tfenv

WORKDIR /deploy

COPY . /deploy

ENTRYPOINT [ "/bin/sh", "./ci/ci-deploy.sh" ]
